# Generated by Django 4.2.5 on 2023-09-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_profile_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='artist_price',
            field=models.IntegerField(),
        ),
    ]
