# Generated by Django 4.2.5 on 2023-09-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_profile_artist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='artist_name',
            field=models.CharField(choices=[('Michael Jackson', 'Michael Jackson'), ('Arijit Singh', 'Arijit Singh'), ('Justin Bieber', 'Justin Bieber'), ('M.F.Hussain', 'M.F. Husain'), ('Guru Randhava', 'Guru Randhava'), ('Zakir Hussain', 'Zakir Hussain'), ('Amjad Ali Khan', 'Amjad Ali Khan'), ('Shilpa Gupta', 'Shilpa Gupta'), ('Paresh Maity', 'Paresh Maity'), ('Parbhu Deva', 'Parbhu Deva'), ('Atul Kasbekar', 'Atul Kasbekar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='artist_type',
            field=models.CharField(choices=[('singer', 'singer'), ('musician', 'musician'), ('painter', 'painter'), ('dancer', 'dancer'), ('photographer', 'photographer'), ('sculptor', 'sculptor')], max_length=100),
        ),
    ]
