# Generated by Django 4.2.5 on 2023-09-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_profile_artist_name_alter_profile_artist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='artist_image',
            field=models.FileField(upload_to='artist_image/'),
        ),
    ]
