# Generated by Django 4.2.5 on 2023-09-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_profile_artist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_artist',
            name='payment_status',
        ),
        migrations.DeleteModel(
            name='TransactionPayment',
        ),
    ]
