# Generated by Django 4.2.5 on 2023-09-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_send_review_review_send'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='send',
            new_name='message',
        ),
    ]
