# Generated by Django 4.2.5 on 2023-09-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_send_review_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=30)),
                ('sec_from', models.DateField(auto_now_add=True)),
                ('profile_pic', models.FileField(default='avtar.png', upload_to='profile')),
            ],
        ),
    ]
