from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.indexpage,name='indexpage'),
    path('about/',views.about,name='about'),
    path('admin_page/',views.admin_page,name='admin_page'),
    path('artist/',views.artist,name='artist'),
    path('track/',views.track,name='track'),
    path('blog_page/',views.blog_page,name='blog_page'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('feedback/',views.feedback,name='feedback'),
    path('customer_review/',views.customer_review,name='customer_review'),
    path('artist_review/',views.artist_review,name='artist_review'),
    path('reviews/',views.reviews,name='reviews'),
    path('artist_index/',views.artist_index,name='artist_index'),
    path('artist_header/',views.artist_header,name='artist_header'),
    path('profile/',views.profile,name='profile'),
    path('artist_add_profile/',views.artist_add_profile,name='artist_add_profile'),
    path('artist_delete_profile/<int:pk>/',views.artist_delete_profile,name='artist_delete_profile'),
    path('artist_view_profile',views.artist_view_profile,name='artist_view_profile'),
    path('artist_edit_profile/<int:pk>/',views.artist_edit_profile,name='artist_edit_profile'),
    path('artist_detail/<int:pk>/',views.artist_detail,name='artist_detail'),
    path('book_artist/<int:pk>/',views.book_artist,name='book_artist'),
    path('bookings/',views.bookings,name='bookings'),
    path('accept_booking/<int:pk>/',views.accept_booking,name='accept_booking'),
    path('reject_booking/<int:pk>/',views.reject_booking,name='reject_booking'),
    path('accepted_booking/',views.accepted_booking,name='accepted_booking'),
    path('rejected_booking/',views.rejected_booking,name='rejected_booking'),
    path('confirmed_booking/',views.confirmed_booking,name='confirmed_booking'),
    path('pending_booking/',views.pending_booking,name='pending_booking'),
    path('all_bookings/',views.all_bookings,name='all_bookings'),
    path('profile/',views.profile,name='profile'),
    path('search/',views.search,name='search'),
    path('artist_singer/',views.artist_singer,name='artist_singer'),
    path('artist_painter/',views.artist_painter,name='artist_painter'),
    path('artist_musician/',views.artist_musician,name='artist_musician'),
    path('artist_dancer/',views.artist_dancer,name='artist_dancer'),
    path('artist_photographer/',views.artist_photographer,name='artist_photographer'),
    path('artist_sculptor/',views.artist_sculptor,name='artist_sculptor'),
    path('view_booking/',views.view_booking,name='view_booking'),
    path('customer_confirmed_booking/',views.customer_confirmed_booking,name='customer_confirmed_booking'),
    path('customer_pending_booking/',views.customer_pending_booking,name='customer_pending_booking'),
    path('customer_accepted_booking/',views.customer_accepted_booking,name='customer_accepted_booking'),
    path('customer_canceled_booking/',views.customer_canceled_booking,name='customer_canceled_booking'),
    path('change_password/',views.change_password,name='change_password'),
    path('logout/',views.logout,name='logout'),


    
]